resource "iosxr_snmp_server" "snmp_server" {
  for_each = { for device in local.devices : device.name => device if try(local.device_config[device.name].snmp_server, null) != null || try(local.defaults.iosxr.configuration.snmp_server, null) != null }
  device   = each.value.name

  location                                  = try(local.device_config[each.value.name].snmp_server.location, local.defaults.iosxr.configuration.snmp_server.location, null)
  contact                                   = try(local.device_config[each.value.name].snmp_server.contact, local.defaults.iosxr.configuration.snmp_server.contact, null)
  trap_source                               = try(local.device_config[each.value.name].snmp_server.trap_source, local.defaults.iosxr.configuration.snmp_server.trap_source, null)
  traps_rf                                  = try(local.device_config[each.value.name].snmp_server.traps_rf, local.defaults.iosxr.configuration.snmp_server.traps_rf, null)
  traps_bfd                                 = try(local.device_config[each.value.name].snmp_server.traps_bfd, local.defaults.iosxr.configuration.snmp_server.traps_bfd, null)
  traps_ntp                                 = try(local.device_config[each.value.name].snmp_server.traps_ntp, local.defaults.iosxr.configuration.snmp_server.traps_ntp, null)
  traps_ethernet_oam_events                 = try(local.device_config[each.value.name].snmp_server.traps_ethernet_oam_events, local.defaults.iosxr.configuration.snmp_server.traps_ethernet_oam_events, null)
  traps_copy_complete                       = try(local.device_config[each.value.name].snmp_server.traps_copy_complete, local.defaults.iosxr.configuration.snmp_server.traps_copy_complete, null)
  traps_snmp_linkup                         = try(local.device_config[each.value.name].snmp_server.traps_snmp_linkup, local.defaults.iosxr.configuration.snmp_server.traps_snmp_linkup, null)
  traps_snmp_linkdown                       = try(local.device_config[each.value.name].snmp_server.traps_snmp_linkdown, local.defaults.iosxr.configuration.snmp_server.traps_snmp_linkdown, null)
  traps_power                               = try(local.device_config[each.value.name].snmp_server.traps_power, local.defaults.iosxr.configuration.snmp_server.traps_power, null)
  traps_config                              = try(local.device_config[each.value.name].snmp_server.traps_config, local.defaults.iosxr.configuration.snmp_server.traps_config, null)
  traps_entity                              = try(local.device_config[each.value.name].snmp_server.traps_entity, local.defaults.iosxr.configuration.snmp_server.traps_entity, null)
  traps_system                              = try(local.device_config[each.value.name].snmp_server.traps_system, local.defaults.iosxr.configuration.snmp_server.traps_system, null)
  traps_bridgemib                           = try(local.device_config[each.value.name].snmp_server.traps_bridgemib, local.defaults.iosxr.configuration.snmp_server.traps_bridgemib, null)
  traps_entity_state_operstatus             = try(local.device_config[each.value.name].snmp_server.traps_entity_state_operstatus, local.defaults.iosxr.configuration.snmp_server.traps_entity_state_operstatus, null)
  traps_entity_redundancy_all               = try(local.device_config[each.value.name].snmp_server.traps_entity_redundancy_all, local.defaults.iosxr.configuration.snmp_server.traps_entity_redundancy_all, null)
  traps_l2vpn_all                           = try(local.device_config[each.value.name].snmp_server.traps_l2vpn_all, local.defaults.iosxr.configuration.snmp_server.traps_l2vpn_all, null)
  traps_l2vpn_vc_up                         = try(local.device_config[each.value.name].snmp_server.traps_l2vpn_vc_up, local.defaults.iosxr.configuration.snmp_server.traps_l2vpn_vc_up, null)
  traps_l2vpn_vc_down                       = try(local.device_config[each.value.name].snmp_server.traps_l2vpn_vc_down, local.defaults.iosxr.configuration.snmp_server.traps_l2vpn_vc_down, null)
  traps_sensor                              = try(local.device_config[each.value.name].snmp_server.traps_sensor, local.defaults.iosxr.configuration.snmp_server.traps_sensor, null)
  traps_fru_ctrl                            = try(local.device_config[each.value.name].snmp_server.traps_fru_ctrl, local.defaults.iosxr.configuration.snmp_server.traps_fru_ctrl, null)
  traps_bgp_cbgp_two_enable                 = try(local.device_config[each.value.name].snmp_server.traps_bgp_cbgp_two_enable, local.defaults.iosxr.configuration.snmp_server.traps_bgp_cbgp_two_enable, null)
  traps_bgp_cbgp_two_updown                 = try(local.device_config[each.value.name].snmp_server.traps_bgp_cbgp_two_updown, local.defaults.iosxr.configuration.snmp_server.traps_bgp_cbgp_two_updown, null)
  traps_bgp_enable_cisco_bgp4_mib           = try(local.device_config[each.value.name].snmp_server.traps_bgp_enable_cisco_bgp4_mib, local.defaults.iosxr.configuration.snmp_server.traps_bgp_enable_cisco_bgp4_mib, null)
  traps_bgp_enable_updown                   = try(local.device_config[each.value.name].snmp_server.traps_bgp_enable_updown, local.defaults.iosxr.configuration.snmp_server.traps_bgp_enable_updown, null)
  traps_isis_adjacency_change               = try(local.device_config[each.value.name].snmp_server.traps_isis_adjacency_change, local.defaults.iosxr.configuration.snmp_server.traps_isis_adjacency_change, null)
  traps_isis_all                            = try(local.device_config[each.value.name].snmp_server.traps_isis_all, local.defaults.iosxr.configuration.snmp_server.traps_isis_all, null)
  traps_isis_area_mismatch                  = try(local.device_config[each.value.name].snmp_server.traps_isis_area_mismatch, local.defaults.iosxr.configuration.snmp_server.traps_isis_area_mismatch, null)
  traps_isis_attempt_to_exceed_max_sequence = try(local.device_config[each.value.name].snmp_server.traps_isis_attempt_to_exceed_max_sequence, local.defaults.iosxr.configuration.snmp_server.traps_isis_attempt_to_exceed_max_sequence, null)
  traps_isis_authentication_failure         = try(local.device_config[each.value.name].snmp_server.traps_isis_authentication_failure, local.defaults.iosxr.configuration.snmp_server.traps_isis_authentication_failure, null)
  traps_isis_authentication_type_failure    = try(local.device_config[each.value.name].snmp_server.traps_isis_authentication_type_failure, local.defaults.iosxr.configuration.snmp_server.traps_isis_authentication_type_failure, null)
  traps_isis_corrupted_lsp_detected         = try(local.device_config[each.value.name].snmp_server.traps_isis_corrupted_lsp_detected, local.defaults.iosxr.configuration.snmp_server.traps_isis_corrupted_lsp_detected, null)
  traps_isis_database_overload              = try(local.device_config[each.value.name].snmp_server.traps_isis_database_overload, local.defaults.iosxr.configuration.snmp_server.traps_isis_database_overload, null)
  traps_isis_id_len_mismatch                = try(local.device_config[each.value.name].snmp_server.traps_isis_id_len_mismatch, local.defaults.iosxr.configuration.snmp_server.traps_isis_id_len_mismatch, null)
  traps_isis_lsp_error_detected             = try(local.device_config[each.value.name].snmp_server.traps_isis_lsp_error_detected, local.defaults.iosxr.configuration.snmp_server.traps_isis_lsp_error_detected, null)
  traps_isis_lsp_too_large_to_propagate     = try(local.device_config[each.value.name].snmp_server.traps_isis_lsp_too_large_to_propagate, local.defaults.iosxr.configuration.snmp_server.traps_isis_lsp_too_large_to_propagate, null)
  traps_isis_manual_address_drops           = try(local.device_config[each.value.name].snmp_server.traps_isis_manual_address_drops, local.defaults.iosxr.configuration.snmp_server.traps_isis_manual_address_drops, null)
  traps_isis_max_area_addresses_mismatch    = try(local.device_config[each.value.name].snmp_server.traps_isis_max_area_addresses_mismatch, local.defaults.iosxr.configuration.snmp_server.traps_isis_max_area_addresses_mismatch, null)
  traps_isis_orig_lsp_buff_size_mismatch    = try(local.device_config[each.value.name].snmp_server.traps_isis_orig_lsp_buff_size_mismatch, local.defaults.iosxr.configuration.snmp_server.traps_isis_orig_lsp_buff_size_mismatch, null)
  traps_isis_own_lsp_purge                  = try(local.device_config[each.value.name].snmp_server.traps_isis_own_lsp_purge, local.defaults.iosxr.configuration.snmp_server.traps_isis_own_lsp_purge, null)
  traps_isis_protocols_supported_mismatch   = try(local.device_config[each.value.name].snmp_server.traps_isis_protocols_supported_mismatch, local.defaults.iosxr.configuration.snmp_server.traps_isis_protocols_supported_mismatch, null)
  traps_isis_rejected_adjacency             = try(local.device_config[each.value.name].snmp_server.traps_isis_rejected_adjacency, local.defaults.iosxr.configuration.snmp_server.traps_isis_rejected_adjacency, null)
  traps_isis_sequence_number_skip           = try(local.device_config[each.value.name].snmp_server.traps_isis_sequence_number_skip, local.defaults.iosxr.configuration.snmp_server.traps_isis_sequence_number_skip, null)
  traps_isis_version_skew                   = try(local.device_config[each.value.name].snmp_server.traps_isis_version_skew, local.defaults.iosxr.configuration.snmp_server.traps_isis_version_skew, null)

  users = try(length(local.device_config[each.value.name].snmp_server.users) == 0, true) ? null : [for user in local.device_config[each.value.name].snmp_server.users : {
    user_name                              = try(user.user_name, null)
    group_name                             = try(user.group_name, null)
    v3_auth_md5_encryption_aes             = try(user.v3_auth_md5_encryption_aes, null)
    v3_auth_md5_encryption_default         = try(user.v3_auth_md5_encryption_default, null)
    v3_auth_sha_encryption_aes             = try(user.v3_auth_sha_encryption_aes, null)
    v3_auth_sha_encryption_default         = try(user.v3_auth_sha_encryption_default, null)
    v3_ipv4                                = try(user.v3_ipv4, null)
    v3_priv_aes_aes_128_encryption_aes     = try(user.v3_priv_aes_aes_128_encryption_aes, null)
    v3_priv_aes_aes_128_encryption_default = try(user.v3_priv_aes_aes_128_encryption_default, null)
    v3_systemowner                         = try(user.v3_systemowner, null)
    }
  ]
  groups = try(length(local.device_config[each.value.name].snmp_server.groups) == 0, true) ? null : [for group in local.device_config[each.value.name].snmp_server.groups : {
    group_name = try(group.group_name, null)
    v3_priv    = try(group.v3_priv, null)
    v3_read    = try(group.v3_read, null)
    v3_write   = try(group.v3_write, null)
    v3_context = try(group.v3_context, null)
    v3_notify  = try(group.v3_notify, null)
    v3_ipv4    = try(group.v3_ipv4, null)
    v3_ipv6    = try(group.v3_ipv6, null)
    }
  ]
  communities = try(length(local.device_config[each.value.name].snmp_server.communities) == 0, true) ? null : [for community in local.device_config[each.value.name].snmp_server.communities : {
    community   = try(community.community, null)
    view        = try(community.view, null)
    ro          = try(community.ro, null)
    rw          = try(community.rw, null)
    sdrowner    = try(community.sdrowner, null)
    systemowner = try(community.systemowner, null)
    ipv4        = try(community.ipv4, null)
    ipv6        = try(community.ipv6, null)
    }
  ]
}
